### ISSUE TITLE
[UI] [Bug] Crash when clicking 'About' command button while exporting

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#41]
1. Open a large file with lots of logos and variants
2. Begin the export process
3. While exporting, click About

Result: When exporting finishes, app crashes

Logs:

```
2024-07-19 09:59:39.046 -07:00 [FTL] Unhandled exception
System.Runtime.InteropServices.COMException (0x80000019): An async operation was not properly started.

Only a single ContentDialog can be open at any time.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
   at LogoSlideMaker.WinUi.MainWindow.ShowAboutDialog(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by jcoliz** [comment]
I think this is fixed in the latest now
