### ISSUE TITLE
[UI] [Bug] Missing logo file causes export to fail with no error

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#45]
Given: A definition with a logo having `path` set to a file that doesn't exist
When: Exporting in UI
Then: Exporting stops with no error given to user
Expected: Error reported to user with missing path, and ideally which logo is causing it

Logs:
```
2024-07-30 15:47:03.928 -07:00 [ERR] ExportSlides: Failed
System.AggregateException: One or more errors occurred. (Export failed: Could not find a part of the path 'C:\Source\jcoliz\AppEcoSlide\placeholderzzzzzz\1x1.svg'.)
 ---> LogoSlideMaker.WinUi.ViewModels.UserErrorException: Export failed: Could not find a part of the path 'C:\Source\jcoliz\AppEcoSlide\placeholderzzzzzz\1x1.svg'.
   at LogoSlideMaker.WinUi.ViewModels.MainViewModel.ExportToAsync(String outPath)
   at LogoSlideMaker.WinUi.MainWindow.<>c__DisplayClass18_0.<<ExportSlides>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by jcoliz** [comment]
Oops. This is not fixed. Actually these changes fixed #45

**Comment by jcoliz** [comment]
Fixed in 5512342af12a9c65f4fe03c3917ef49dce17a859
