### ISSUE TITLE
[UI] [Bug] Specifying a logo with no path causes export to fail with no error

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#46]
Given: A definition with a logo having no path set
When: Exporting in UI
Then: Exporting stops with no error given to user
Expected: Error reported to user explaining the problem in a way they can solve, e,g, "Logo `something` has no path set."

Alternately, could just ignore this case. If the logo is never used, we'd never be hurt by not having it. We could just filter it out on import, and then if user tried to use it, would get missing image visual.

Logs:
```
2024-07-30 15:39:43.242 -07:00 [ERR] ExportSlides: Failed
System.AggregateException: One or more errors occurred. (Export failed: Could not find a part of the path 'C:\Source\jcoliz\AppEcoSlide\'.)
 ---> LogoSlideMaker.WinUi.ViewModels.UserErrorException: Export failed: Could not find a part of the path 'C:\Source\jcoliz\AppEcoSlide\'.
   at LogoSlideMaker.WinUi.ViewModels.MainViewModel.ExportToAsync(String outPath)
   at LogoSlideMaker.WinUi.MainWindow.<>c__DisplayClass18_0.<<ExportSlides>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by jcoliz** [comment]
It would be helpful to support this case. Should just show the title, and the empty logo rectangle. Would be handy for rapid prototyping.

**Comment by jcoliz** [comment]
Is fixed now
