### ISSUE TITLE
[UI] [Error] Add user-facing error when template not found on export

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#47]
Given: A definition with a `template.slides` line pointing to a file which doesn't exist
When: Exporting it
Then: Fails silently
Expected: Error message explaining the problem to user

Logs

```
2024-08-01 08:34:44.043 -07:00 [ERR] ExportSlides: Failed
System.AggregateException: One or more errors occurred. (Export failed: Template not found at C:\Source\jcoliz\AppEcoSlide\template-2924-08-01.pptx)
 ---> LogoSlideMaker.WinUi.ViewModels.UserErrorException: Export failed: Template not found at C:\Source\jcoliz\AppEcoSlide\template-2924-08-01.pptx
   at LogoSlideMaker.WinUi.ViewModels.MainViewModel.ExportToAsync(String outPath)
   at LogoSlideMaker.WinUi.MainWindow.<>c__DisplayClass18_0.<<ExportSlides>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
```

**Comment by jcoliz** [comment]
Fixed with same fix as #46
