### ISSUE TITLE
[UI][Bug] Exception thrown in MainViewModel.PopulateLayout

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/LogoSlideMaker#49]
## Repro steps
1. Loaded LogoSlideMaker.WinUi\Sample\sample-packed.toml into previewer
2. Loaded sample\sample.toml into previewer
3. Displays error "Opening file failed": "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')"

## Root cause investigation

This code looks suspect! Is not considering whether _slideNumber is in range at all. That said, I don't really understand why _slideNumber is NOT in range because incoming definition does have a variant.

```c#
var variant = _definition.Variants.Count > 0 ? _definition.Variants[_slideNumber] : new Variant();
```

Hmm, this may be a timing problem. In this case the OLD file, sample-packed does not have a variant. So for this moment, are we getting the count of variants from the OLD file, and then trying to read the variant out of the NEW file?? No, that's backwards. Will need to investigate further.

## Logs
```
2024-09-16 12:53:32.762 -07:00 [INF] OpenDocument: Selected OK C:\Source\jcoliz\LogoSlideMaker\sample\sample.toml
2024-09-16 12:53:32.766 -07:00 [ERR] LoadDefinitionAsync: Stream load Failed
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LogoSlideMaker.WinUi.ViewModels.MainViewModel.PopulateLayout()
   at LogoSlideMaker.WinUi.ViewModels.MainViewModel.<>c__DisplayClass68_0.<LoadDefinitionAsync>b__0()
2024-09-16 12:53:32.799 -07:00 [DBG] LoadDefinitionAsync: Launched
2024-09-16 12:53:36.161 -07:00 [INF] ShowErrorAsync: OK Opening file failed Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```

## Found in version

ci-3420 9d78c00046b52a8144e0f008c679b30c737a8c7d

**Comment by jcoliz** [comment]
It seems I cannot load ANY file, after having loaded sample-packed.toml!

**Comment by jcoliz** [comment]
Does not repro in the debugger. So almost certainly a timing problem.

**Comment by jcoliz** [comment]
Also doesn't repro using locally-built copy in Release (!?)

**Comment by jcoliz** [comment]
Also doesn't repro again after re-install of same bits. Will add some extra logging and close.
